#! /usr/bin/bash

# Forza la richiesta della password all'inizio
sudo -v

# Nome dei processi da chiudere
PROCESS_1="bitcoind"
PROCESS_2="b-shutoff"

# Attesa in secondi prima dello spegnimento/ravvio
TIMEOUT=7

# Funzione per verificare se il processo è in esecuzione
is_process_running() {
    pgrep "$PROCESS_NAME" > /dev/null 2>&1
}

PROCESS_NAME=$PROCESS_1
echo "Chiusura di $PROCESS_NAME"
bitcoin-cli stop
# Loop finché il processo è in esecuzione
while is_process_running; do
    echo -n "."
    sleep 1
done

echo
PROCESS_NAME=$PROCESS_2
echo "Chiusura di $PROCESS_NAME"
# Loop finché il processo è in esecuzione
while is_process_running; do
    echo -n "."
    sleep 1
done

#Con "nodeshutdown -r" fa il reboot anzichè lo spegnimento
if [ $# -gt 0 ] && [ $1 == "-r" ]; then
  OPERAZIONE="Riavvio"
  COMANDO="sudo reboot"
else
  OPERAZIONE="Spegnimento"
  COMANDO="sudo shutdown -h now"
fi
echo
echo -e "\a"
echo "Tutti i processi sono stati chiusi. $OPERAZIONE in $TIMEOUT secondi..."
sleep $TIMEOUT
$COMANDO